all: \
basicTextFmt.html \
bulletLists_withNesting.html \
emphasis_inBulletList.html \
numberedLists_withNesting.html \
numberedList_onOneLevel.html \
numberedList_withWrappedLines.html

basicTextFmt.html: \
  basicTextFmt.md

	cmd /c mdpl /OUT $@ $^

bulletLists_withNesting.html: \
  bulletLists_withNesting.md

	cmd /c mdpl /OUT $@ $^

emphasis_inBulletList.html: \
  emphasis_inBulletList.md

	cmd /c mdpl /OUT $@ $^

numberedLists_withNesting.html: \
  numberedLists_withNesting.md

	cmd /c mdpl /OUT $@ $^

numberedList_onOneLevel.html: \
  numberedList_onOneLevel.md

	cmd /c mdpl /OUT $@ $^

numberedList_withWrappedLines.html: \
  numberedList_withWrappedLines.md

	cmd /c mdpl /OUT $@ $^
